version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./monitoring/prometheus/:/etc/prometheus/"
    restart: always
    entrypoint: sh -c "cp /etc/prometheus/prometheus.yml /etc/prometheus/config.yml && exec prometheus --config.file=/etc/prometheus/config.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - "19999:19999"
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined

volumes:
  grafana_data: